import {ExtensionData} from '../../../../../src/common/types/plugins/modules';

export async function fetchExtensionList(): Promise<ExtensionData[]> {
  return [
    {
      url: 'https://github.com/mamei16/LLM_Web_search',
      title: 'LLM_Web_search',
      description: 'Lets your LLM search the web.',
      stars: 155,
    },
    {
      url: 'https://github.com/erew123/alltalk_tts',
      title: 'AllTalk TTS',
      description: 'Advanced TTS engine with many features.',
      stars: 828,
    },
    {
      url: 'https://github.com/Vasyanator/google_translate_plus',
      title: 'google_translate_plus',
      description: 'Improved Google Translate extension.',
      stars: 2,
    },
    {
      url: 'https://github.com/brucepro/Memoir',
      title: 'Memoir+',
      description: 'Adds memory and personality to your chatbot.',
      stars: 164,
    },
    {
      url: 'https://github.com/RandomInternetPreson/Lucid_Vision',
      title: 'Lucid_Vision',
      description: 'Integrates advanced vision models.',
      stars: 36,
    },
    {
      url: 'https://github.com/RandomInternetPreson/LucidWebSearch',
      title: 'LucidWebSearch',
      description: 'Web search extension with OCR support.',
      stars: 62,
    },
    {
      url: 'https://github.com/innightwolfsleep/text-generation-webui-telegram_bot',
      title: 'telegram_bot',
      description: 'Telegram bot interface for text-generation-webui.',
      stars: 102,
    },
    {
      url: 'https://github.com/SicariusSicariiStuff/Diffusion_TTS',
      title: 'Diffusion_TTS',
      description: 'Realistic and fast local TTS using TorToiSe.',
      stars: 59,
    },
    {
      url: 'https://github.com/SkinnyDevi/webui_tavernai_charas',
      title: 'Integrated TavernUI Characters',
      description: 'Search, download, and manage TavernAI characters.',
      stars: 58,
    },
    {
      url: 'https://github.com/DavG25/text-generation-webui-code_syntax_highlight',
      title: 'code_syntax_highlight',
      description: 'Adds syntax highlighting to code snippets.',
      stars: 62,
    },
    {
      url: 'https://github.com/Anglebrackets/web_rag',
      title: 'web_rag',
      description: 'Retrieval-Augmented Generation from web content.',
      stars: 16,
    },
    {
      url: 'https://github.com/Trojaner/text-generation-webui-stable_diffusion',
      title: 'stable_diffusion',
      description: 'Integrates Stable Diffusion image generation.',
      stars: 51,
    },
    {
      url: 'https://github.com/ill13/SpeakLocal/',
      title: 'SpeakLocal',
      description: "Local TTS using your host's native engine.",
      stars: 26,
    },
    {
      url: 'https://github.com/p-e-w/chatbot_clinic',
      title: 'Chatbot Clinic',
      description: 'Develop and compare different chatbot personalities.',
      stars: 53,
    },
    {
      url: 'https://github.com/GuizzyQC/sd_api_pictures_tag_injection',
      title: 'sd_api_pictures_tag_injection',
      description: 'Enhances character image consistency with SD.',
      stars: 24,
    },
    {
      url: 'https://github.com/theubie/complex_memory',
      title: 'complex_memory',
      description: 'KoboldAI-like memory for conversations.',
      stars: 105,
    },
    {
      url: 'https://github.com/BoredBrownBear/text-generation-webui-model_ducking',
      title: 'Model Ducking',
      description: 'Automatically unloads and reloads models to save VRAM.',
      stars: 15,
    },
    {
      url: 'https://github.com/Touch-Night/more_translators',
      title: 'More translators',
      description: 'Adds more translation options.',
      stars: 6,
    },
    {
      url: 'https://github.com/Hellisotherpeople/llm_steer-oobabooga/tree/main',
      title: 'llm_steer-oobabooga',
      description: 'Steer LLM outputs towards specific topics.',
      stars: 40,
    },
    {
      url: 'https://github.com/FartyPants/VirtualLora',
      title: 'Virtual Lora',
      description: 'Advanced LoRA management system.',
      stars: 13,
    },
    {
      url: 'https://github.com/tijo95/piper_tts',
      title: 'piper_tts',
      description: 'Fast and multilingual TTS using Piper.',
      stars: 11,
    },
    {
      url: 'https://github.com/simbake/web_search',
      title: 'Web_Search',
      description: 'Simple Google Search integration.',
      stars: 91,
    },
    {
      url: 'https://github.com/BuffMcBigHuge/text-generation-webui-edge-tts',
      title: 'edge_tts',
      description: 'Microsoft Edge TTS with RVC support.',
      stars: 38,
    },
    {
      url: 'https://github.com/brucepro/LibreTranslate-extension-for-text-generation-webui',
      title: 'LibreTranslate',
      description: 'Offline translation using LibreTranslate.',
      stars: 1,
    },
    {
      url: 'https://github.com/xr4dsh/CodeRunner',
      title: 'CodeRunner',
      description: 'Allows your LLM to execute code.',
      stars: 25,
    },
    {
      url: 'https://github.com/FartyPants/Playground',
      title: 'Playground for Writers',
      description: 'Advanced notebook with extra features.',
      stars: 128,
    },
    {
      url: 'https://github.com/TheInvisibleMage/ooba_dieroller',
      title: 'Ooba_Dieroller',
      description: 'Dice roller for tabletop RPGs.',
      stars: 4,
    },
    {
      url: 'https://github.com/FartyPants/Twinbook',
      title: 'Twinbook',
      description: 'Combined chat and notebook with advanced controls.',
      stars: 28,
    },
    {
      url: 'https://github.com/yhyu13/Emotivoice_TTS',
      title: 'Emotivoice_TTS',
      description: 'Fast Chinese-English TTS by NetEase.',
      stars: 4,
    },
    {
      url: 'https://github.com/bekkayya/session_manager/',
      title: 'Session_Manager',
      description: 'Save and load sessions with parameters.',
      stars: 7,
    },
    {
      url: 'https://github.com/kanttouchthis/text_generation_webui_xtts',
      title: 'XTTSv2',
      description: 'XTTSv2 TTS with narrator feature.',
      stars: 143,
    },
    {
      url: 'https://github.com/ThereforeGames/echoproof',
      title: 'Echoproof',
      description: 'Reduces LLM repetition in conversations.',
      stars: 33,
    },
    {
      url: 'https://github.com/RandomInternetPreson/text-generation-webui-barktts',
      title: 'bark_tts (forked and updated)',
      description: 'Updated Bark TTS with multi-language support.',
      stars: 9,
    },
    {
      url: 'https://github.com/minemo/text-generation-webui-barktts',
      title: 'bark_tts (original)',
      description: 'Multi-lingual Bark TTS.',
      stars: 35,
    },
    {
      url: 'https://github.com/asadfgglie/voicevox_tts',
      title: 'voicevox_tts',
      description: 'Japanese TTS with optional translation.',
      stars: 4,
    },
    {
      url: 'https://github.com/sammyf/moztts',
      title: 'moztts',
      description: 'Integrates Mozilla TTS engine.',
      stars: 15,
    },
    {
      url: 'https://github.com/jason-brian-anderson/long_term_memory_with_qdrant',
      title: 'Long term memory with qdrant vector database',
      description: 'Long-term memory using qdrant database.',
      stars: 45,
    },
    {
      url: 'https://github.com/GiusTex/EdgeGPT',
      title: 'EdgeGPT',
      description: 'Provides internet access for your bot.',
      stars: 126,
    },
    {
      url: 'https://github.com/xanthousm/text-gen-webui-ui_tweaks',
      title: 'UI Tweaks',
      description: 'Improves UI with sticky tabs and sidebar.',
      stars: 21,
    },
    {
      url: 'https://github.com/ill13/AutoSave/',
      title: 'AutoSave',
      description: 'Automatically saves generated text.',
      stars: 21,
    },
    {
      url: 'https://github.com/ChobPT/oobaboogas-webui-langchain_agent/',
      title: 'webui_langchain_agent',
      description: 'Creates a Langchain agent for the WebUI.',
      stars: 73,
    },
    {
      url: 'https://github.com/SnowMasaya/text-generation-webui/tree/deepl/extensions/deepl_translate',
      title: 'deepl_translator',
      description: 'DeepL translation for input and output.',
      stars: 1,
    },
    {
      url: 'https://github.com/chrisrude/oobabot-plugin',
      title: 'oobabot',
      description: 'Discord bot with command-line and GUI modes.',
      stars: 40,
    },
    {
      url: 'https://github.com/wawawario2/long_term_memory',
      title: 'long_term_memory',
      description: 'Sophisticated long-term memory for chatbots.',
      stars: 304,
    },
    {
      url: 'https://github.com/dibrale/webui-autonomics',
      title: 'webui-autonomics',
      description: 'Dynamically adjusts parameters based on emotional tone.',
      stars: 32,
    },
    {
      url: 'https://github.com/danikhan632/guidance_api',
      title: 'Guidance API',
      description: 'Enables guidance for generating schemaful data.',
      stars: 34,
    },
    {
      url: 'https://github.com/hallucinate-games/oobabooga-jsonformer-plugin',
      title: 'jsonformer',
      description: 'Forces model output to conform to JSON schema.',
      stars: 25,
    },
    {
      url: 'https://github.com/FartyPants/FPreloader',
      title: 'FPreloader',
      description: 'Reloads extensions without rebooting the WebUI.',
      stars: 15,
    },
    {
      url: 'https://github.com/elPatrixF/dynamic_context',
      title: 'dynamic_context',
      description: 'Adds dynamic time and date context.',
      stars: 11,
    },
    {
      url: 'https://github.com/janvarev/api_advanced',
      title: 'api_advanced',
      description: 'Enhanced API with advanced translation logic.',
      stars: 11,
    },
    {
      url: 'https://github.com/janvarev/multi_translate',
      title: 'multi_translate',
      description: 'Expanded Google Translate with more options.',
      stars: 25,
    },
    {
      url: 'https://github.com/ChobPT/text-generation-webui-discord_bot',
      title: 'discord_bot',
      description: 'Discord integration via webhooks.',
      stars: 13,
    },
  ];
}
