import {ExtensionData} from '../../../../../src/common/types/plugins/modules';

export async function fetchExtensionList(): Promise<ExtensionData[]> {
  return [
    {
      url: 'https://github.com/altoiddealer/ad_discordbot',
      title: 'ad_discordbot',
      description: 'Advanced Discord bot with image generation, TTS, voice channels, and extensive customization.',
      stars: 0,
    },
    {
      url: 'https://github.com/brucepro/Memoir',
      title: 'Memoir+',
      description: 'Adds short and long term memories, emotional polarity tracking for personas.',
      stars: 224,
    },
    {
      url: 'https://github.com/mistbyte-ai/websearch-mistbyte',
      title: 'WebSearch API (MistByte)',
      description: 'Local, explicit web search integration without hallucinations.',
      stars: 0,
    },
    {
      url: 'https://github.com/mamei16/context-progress-bar-text-generation-webui',
      title: 'context-progress-bar',
      description: 'Real-time progress bar showing context window usage.',
      stars: 6,
    },
    {
      url: 'https://github.com/innightwolfsleep/text-generation-webui-telegram_bot',
      title: 'telegram_bot',
      description: 'Telegram bot interface for text-generation-webui.',
      stars: 102,
    },
    {
      url: 'https://github.com/mamei16/LLM_Web_search',
      title: 'LLM_Web_search',
      description: 'Give your LLM the ability to search the web.',
      stars: 275,
    },
    {
      url: 'https://github.com/ill13/AutoSave/',
      title: 'AutoSave',
      description: 'Auto save extension for generated text, 100% local.',
      stars: 25,
    },
    {
      url: 'https://github.com/SicariusSicariiStuff/Diffusion_TTS',
      title: 'Diffusion_TTS',
      description: 'Realistic TTS using faster TorToiSe autoregressive model.',
      stars: 69,
    },
    {
      url: 'https://github.com/SkinnyDevi/skdv_comfyui',
      title: 'SKDV ComfyUI Image Generation',
      description: 'ComfyUI image generation with custom workflows and character prompts.',
      stars: 14,
    },
    {
      url: 'https://github.com/SkinnyDevi/webui_tavernai_charas',
      title: 'SKDV Integrated TavernUI Characters',
      description: 'Search, download, and manage TavernAI character cards.',
      stars: 69,
    },
    {
      url: 'https://github.com/FartyPants/Playground',
      title: 'Playground for Writers',
      description: 'Advanced notebook with inline instruct, select and insert, LoRA-Rama.',
      stars: 146,
    },
    {
      url: 'https://github.com/FartyPants/VirtualLora',
      title: 'Virtual Lora',
      description: 'State of the art LoRA management with custom collections and checkpoints.',
      stars: 19,
    },
    {
      url: 'https://github.com/FartyPants/Twinbook',
      title: 'Twinbook',
      description: 'Combines chat and notebook with dual-side control.',
      stars: 42,
    },
    {
      url: 'https://github.com/erew123/alltalk_tts',
      title: 'AllTalk v2 TTS',
      description: 'Multi-engine TTS with Coqui XTTS, F5 TTS, Piper, Parler, and RVC support.',
      stars: 2242,
    },
    {
      url: 'https://github.com/rsxdalv/text-to-tts-webui',
      title: 'Text To TTS WebUI',
      description: 'Connect to TTS WebUI for Kokoro TTS and ChatterBox TTS.',
      stars: 2,
    },
    {
      url: 'https://github.com/okazaki10/Emotivoice_RVC_TTS',
      title: 'Emotivoice_RVC_TTS',
      description: 'Emotivoice extension with RVC custom voice.',
      stars: 0,
    },
    {
      url: 'https://github.com/h43lb1t0/KokoroTtsTexGernerationWebui',
      title: 'Kokoro TTS',
      description: 'TTS with Kokoro v1, 26 different voices.',
      stars: 21,
    },
    {
      url: 'https://github.com/marcos33998/GPT-SoVITS_TTS',
      title: 'GPT-SoVITS_TTS',
      description: 'TTS using GPT-SoVits api_v2.',
      stars: 0,
    },
    {
      url: 'https://github.com/FartyPants/FPreloader',
      title: 'FPreloader',
      description: 'Reload extensions without rebooting web UI.',
      stars: 19,
    },
    {
      url: 'https://github.com/brucepro/LibreTranslate-extension-for-text-generation-webui',
      title: 'LibreTranslate',
      description: 'Offline translation using LibreTranslate local server.',
      stars: 3,
    },
    {
      url: 'https://github.com/hallucinate-games/oobabooga-jsonformer-plugin',
      title: 'jsonformer',
      description: 'Force model output to conform to JSON schema.',
      stars: 28,
    },
    {
      url: 'https://github.com/theubie/complex_memory',
      title: 'complex_memory',
      description: 'KoboldAI-like memory extension with keyword-based injection.',
      stars: 108,
    },
    {
      url: 'https://github.com/Vasyanator/google_translate_plus',
      title: 'google_translate_plus',
      description: 'Improved Google Translate with paragraph preservation and large text support.',
      stars: 4,
    },
    {
      url: 'https://github.com/RandomInternetPreson/Lucid_Vision',
      title: 'Lucid_Vision',
      description: 'Integrates advanced vision models for image conversations.',
      stars: 57,
    },
    {
      url: 'https://github.com/RandomInternetPreson/LucidWebSearch',
      title: 'LucidWebSearch',
      description: 'Web search with Chrome and nouget OCR model support.',
      stars: 72,
    },
    {
      url: 'https://github.com/DavG25/text-generation-webui-code_syntax_highlight',
      title: 'code_syntax_highlight',
      description: 'Syntax highlighting for code snippets with copy-to-clipboard.',
      stars: 69,
    },
    {
      url: 'https://github.com/Anglebrackets/web_rag',
      title: 'web_rag',
      description: 'Retrieval-Augmented Generation from web content using Links browser.',
      stars: 23,
    },
    {
      url: 'https://github.com/Trojaner/text-generation-webui-stable_diffusion',
      title: 'stable_diffusion',
      description: 'Integrates Stable Diffusion with face swapping support.',
      stars: 58,
    },
    {
      url: 'https://github.com/ill13/SpeakLocal/',
      title: 'SpeakLocal',
      description: "TTS using host's native engine, 100% local and low resource.",
      stars: 32,
    },
    {
      url: 'https://github.com/p-e-w/chatbot_clinic',
      title: 'Chatbot Clinic',
      description: 'Develop chatbot characters by testing multiple versions simultaneously.',
      stars: 61,
    },
    {
      url: 'https://github.com/GuizzyQC/sd_api_pictures_tag_injection',
      title: 'sd_api_pictures_tag_injection',
      description: 'Inject character tags into SD prompts for stable character images.',
      stars: 24,
    },
    {
      url: 'https://github.com/BoredBrownBear/text-generation-webui-model_ducking',
      title: 'Model Ducking',
      description: 'Auto-unload models after prompts to free VRAM.',
      stars: 17,
    },
    {
      url: 'https://github.com/Touch-Night/more_translators',
      title: 'More translators',
      description: 'Adds Baidu, Google, Bing, DeepL and more translators.',
      stars: 11,
    },
    {
      url: 'https://github.com/Hellisotherpeople/llm_steer-oobabooga/tree/main',
      title: 'llm_steer-oobabooga',
      description: 'Steer LLM outputs using activation engineering with steering vectors.',
      stars: 44,
    },
    {
      url: 'https://github.com/tijo95/piper_tts',
      title: 'piper_tts',
      description: 'Fast multilingual TTS using Piper model.',
      stars: 14,
    },
    {
      url: 'https://github.com/BuffMcBigHuge/text-generation-webui-edge-tts',
      title: 'edge_tts',
      description: "Microsoft's Edge TTS with RVC support.",
      stars: 42,
    },
    {
      url: 'https://github.com/xr4dsh/CodeRunner',
      title: 'CodeRunner',
      description: 'Code execution environment using thebe and jupyter server.',
      stars: 30,
    },
    {
      url: 'https://github.com/TheInvisibleMage/ooba_dieroller',
      title: 'Ooba_Dieroller',
      description: 'Dice notation roller for tabletop RPGs.',
      stars: 5,
    },
    {
      url: 'https://github.com/yhyu13/Emotivoice_TTS',
      title: 'Emotivoice_TTS',
      description: 'Fast Chinese-English bilingual TTS by NetEase.',
      stars: 5,
    },
    {
      url: 'https://github.com/bekkayya/session_manager/',
      title: 'Session_Manager',
      description: 'Save/load data and parameters between sessions with autosaving.',
      stars: 7,
    },
    {
      url: 'https://github.com/kanttouchthis/text_generation_webui_xtts',
      title: 'XTTSv2',
      description: 'XTTSv2 TTS with narrator feature for asterisk text.',
      stars: 156,
    },
    {
      url: 'https://github.com/ThereforeGames/echoproof',
      title: 'Echoproof',
      description: 'Minimizes LLM repetition by injecting history into negative prompt.',
      stars: 33,
    },
    {
      url: 'https://github.com/RandomInternetPreson/text-generation-webui-barktts',
      title: 'bark_tts (updated fork)',
      description: 'Bark TTS with improved special character recognition.',
      stars: 9,
    },
    {
      url: 'https://github.com/minemo/text-generation-webui-barktts',
      title: 'bark_tts (original)',
      description: 'Suno-AI Bark TTS with multi-language and sound effects.',
      stars: 33,
    },
    {
      url: 'https://github.com/asadfgglie/voicevox_tts',
      title: 'voicevox_tts',
      description: 'Japanese TTS using VOICEVOX with auto-translation.',
      stars: 6,
    },
    {
      url: 'https://github.com/GiusTex/EdgeGPT',
      title: 'EdgeGPT',
      description: 'Quick internet access for your bot using EdgeGPT.',
      stars: 124,
    },
    {
      url: 'https://github.com/xanthousm/text-gen-webui-ui_tweaks',
      title: 'UI Tweaks',
      description: 'Sticky tabs and hidden sidebar to reduce scrolling.',
      stars: 23,
    },
    {
      url: 'https://github.com/ChobPT/oobaboogas-webui-langchain_agent/',
      title: 'webui_langchain_agent',
      description: 'Langchain agent using WebUI API and Wikipedia.',
      stars: 73,
    },
    {
      url: 'https://github.com/SnowMasaya/text-generation-webui/tree/deepl/extensions/deepl_translate',
      title: 'deepl_translator',
      description: 'Input and output translation using DeepL.',
      stars: 1,
    },
    {
      url: 'https://github.com/chrisrude/oobabot-plugin',
      title: 'oobabot',
      description: 'Discord bot with command-line and GUI modes, easy setup.',
      stars: 44,
    },
    {
      url: 'https://github.com/wawawario2/long_term_memory',
      title: 'long_term_memory',
      description: 'Sophisticated long term memory for chat mode bots.',
      stars: 304,
    },
    {
      url: 'https://github.com/dibrale/webui-autonomics',
      title: 'webui-autonomics',
      description: 'Dynamically adjust parameters to mirror emotional tone.',
      stars: 32,
    },
    {
      url: 'https://github.com/danikhan632/guidance_api',
      title: 'Guidance API',
      description: 'Enable guidance for generating schemaful data.',
      stars: 36,
    },
    {
      url: 'https://github.com/elPatrixF/dynamic_context',
      title: 'dynamic_context',
      description: 'Replaces {{time}} and {{date}} with current values.',
      stars: 11,
    },
    {
      url: 'https://github.com/janvarev/api_advanced',
      title: 'api_advanced',
      description: 'Enhanced API with auto-translation and caching.',
      stars: 11,
    },
    {
      url: 'https://github.com/janvarev/multi_translate',
      title: 'multi_translate',
      description: 'Multiple translation engines with toggle functionality.',
      stars: 28,
    },
    {
      url: 'https://github.com/ChobPT/text-generation-webui-discord_bot',
      title: 'discord_bot',
      description: 'Discord integration via webhooks.',
      stars: 13,
    },
  ];
}
